// src/lib/agents/morning/prompt.ts
//
// Morning Agent prompts. The system prompt is cached (1h TTL) — the user
// message is regenerated each run with fresh context.
//
// IMPORTANT: time-of-day greeting logic is intentionally NOT here. This is
// the Morning Agent — it always greets as morning. The greeting comes out
// in the structured `greeting` field, generated by the LLM.

import "server-only";

export interface MorningPromptContext {
  ownerName: string;
  businessName: string;
  todaysEvents: Array<{
    time: string;
    title: string;
    type?: "meeting" | "deadline" | "reminder";
  }>;
  yesterdayMetrics: {
    revenue?: number;
    orders?: number;
    visitors?: number;
    leads?: number;
  };
  pendingTasks: Array<{
    title: string;
    priority: "high" | "medium" | "low";
    dueDate?: string;
  }>;
  recentUpdates: string[];
}

export const MORNING_AGENT_SYSTEM_PROMPT = `אתה סוכן הבוקר של Spike Engine — מערכת שמשרתת בעלי עסקים קטנים-בינוניים בישראל.

התפקיד: לייצר בריפינג בוקר קצר וממוקד לבעל העסק.

טון:
- מקצועי, חם, ישיר. עברית טבעית, לא תרגומית.
- מספרים מדויקים, לא עיגולים. אם המכירות עלו ב-7.3%, כתוב 7.3% — לא "כמעט 10%".
- כבוד. בעל העסק יודע מה הוא עושה. אתה לא מסביר לו את המקצוע שלו, רק מציג נתונים.

כללי שפה:
- פתח תמיד ב"בוקר טוב, [שם הבעלים]". זה סוכן בוקר, לא משנה מתי הוא רץ.
- לעולם אל תזכיר שאתה AI, בינה מלאכותית, או "בוט".
- אל תשתמש ב"משתמש" או "לקוח" — בעל העסק / [שם פרטי].
- כשבעל העסק זכר השתמש בלשון זכר, נקבה בנקבה. אם לא ידוע, לשון סתמית ("אפשר", "כדאי").

כללי תוכן:
- אם אין נתונים בשדה — החזר null או מערך ריק. אל תמציא.
- שדות מערך (insights, thingsCompleted, todaysSchedule): 1-3 פריטים, כל אחד משפט קצר.
- callToAction: דבר אחד ספציפי שאפשר לעשות היום. לא ערפל.

ענה רק ב-JSON תקני התואם לסכמה. שום טקסט מחוץ ל-JSON.`;

export function buildMorningUserMessage(context: MorningPromptContext): string {
  const today = new Intl.DateTimeFormat("he-IL", {
    weekday: "long",
    day: "numeric",
    month: "long",
  }).format(new Date());

  const events =
    context.todaysEvents.length > 0
      ? context.todaysEvents.map((e) => `- ${e.time}: ${e.title}`).join("\n")
      : "אין פגישות מתוכננות";

  const metrics =
    Object.entries(context.yesterdayMetrics)
      .filter(([, v]) => v != null)
      .map(([k, v]) => {
        const labels: Record<string, string> = {
          revenue: "הכנסות",
          orders: "הזמנות",
          visitors: "מבקרים",
          leads: "לידים",
        };
        return `- ${labels[k] ?? k}: ${v}`;
      })
      .join("\n") || "אין נתונים מאתמול";

  const tasks =
    context.pendingTasks.length > 0
      ? context.pendingTasks
          .slice(0, 5)
          .map((t) => `- ${t.title}`)
          .join("\n")
      : "אין משימות פתוחות";

  const updates =
    context.recentUpdates.length > 0
      ? context.recentUpdates.map((u) => `- ${u}`).join("\n")
      : "אין עדכונים";

  return `היום ${today}.

עסק: ${context.businessName}
בעלים: ${context.ownerName}

לוז היום:
${events}

נתוני אתמול:
${metrics}

משימות פתוחות:
${tasks}

עדכונים אחרונים:
${updates}

צור בריפינג בוקר קצר ומועיל.`;
}
